name: OraxenUIFilter
main: me.apatuka.OraxenUIFilter.OraxenUIFilter
version: 1.4
api-version: '1.16'
author: apatuka
depend:
  - MythicLib
  - MMOItems
softdepend:
  - Oraxen
  - ItemsAdder
  - Nexo
commands:
  uimanager:
    permission: CustomitemUIfilter.access
    description: UIFilter
    aliases: []